apiVersion: "aerogear.org/v1alpha1"
kind: "MobileClient"
metadata:
  name: "example"
spec:
  clientType: "android"
  name: "android-app"
  appIdentifier: "test.aerogear.org"
  apiKey: "bf997a82-9415-40fc-8480-e222a97d55b4"

